name: github.com/Dao-AILab/flash-attention
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        version: [v2.7.4.post1, v2.7.4, v2.7.3, v2.7.2, v2.7.2.post1]
        platform: [amd64, arm64]
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-docker-action@v4
      - run: |
           docker build --platform=linux/${{ matrix.platform }} -f Dockerfile.flash-attn -o type=local,dest=dist .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: flash-attention-${{ matrix.platform }}-${{ matrix.version }}
          path: |
            dist/*.whl
      - uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: 9c8055ce7e6e388a6e58e66249df0e27
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ml-wheels
          source-dir: dist
          destination-dir: ./
