name: github.com/triton-lang/triton
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        version: [release/2.0.x, release/2.1.x, release/2.2.x, release/2.3.x, release/3.0.x, release/3.1.x, release/3.2.x, release/3.3.x]
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: |
          git clone https://github.com/triton-lang/triton
          cd triton

          pip install -r python/requirements.txt
          python setup.py bdist_wheel
