name: github.com/triton-lang/triton
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        version: [3.0.x, 3.1.x, 3.2.x, 3.3.x]
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: |
          git clone -b release/${{ matrix.version }} https://github.com/triton-lang/triton
          cd triton

          pip install ninja cmake setuptools wheel pybind11 lit
          cd python
          python setup.py bdist_wheel
        env:
          MAX_JOBS: 2
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: triton-${{ matrix.os }}-${{ matrix.version }}
          path: |
            triton/python/dist/*.whl
      - uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: 9c8055ce7e6e388a6e58e66249df0e27
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ml-wheels
          source-dir: triton/python/dist
          destination-dir: ./
