name: github.com/triton-lang/triton
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        version: [3.0.x, 3.1.x, 3.2.x, 3.3.x]
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: |
          git clone -b release/${{ matrix.version }} https://github.com/triton-lang/triton
          cd triton

          pip install ninja cmake setuptools wheel pybind11 lit
          cd python
          MAX_JOBS=2 python setup.py bdist_wheel
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: triton-${{ matrix.os }}-${{ matrix.version }}
          path: |
            triton/dist/*.whl
